server:
  port: 8080


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/plants_shop"
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    prefix-url: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: minato111ts@gmail.com
    password: kent dsys ican yjqa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  signerKey: kAcU+KVf2Haa7BqtxYeQyhrSEAVwarlkUSh79ItPHRwSkkIPCpgKWaU+Rr/zJh0Z
  valid-duration: 3600
  refreshable-duration: 604800
password:
  kent dsys ican yjqa

